### PR TITLE
Adding a license

### PR DESCRIPTION
**Pull request by gxalpha**
You don't have a license for your project which can be a problem if someone wants to use it, like here: https://github.com/obsproject/rfcs/pull/15.
I'd propose GPLv2 as it is a good license for open source projects.

### CODE REVIEW

**Comment by signalwerk** [comment]
@lvsti thank you for your awesome code and help to the open source community. I completely support @gxalpha in his strive for clarity. In https://github.com/obsproject/rfcs/pull/15 I started the discussion, since people were using your code. I think it would also be save to remove the apple-licence, since it has the [MIT](https://en.wikipedia.org/wiki/MIT_License) characteristics and you can re-licence it. I think it's save to remove it from all the files. I know the MIT/GPLv2 debate. Since people would love to use your code in a GPLv2 project both would work for them.

**Comment by lvsti** [comment]
Hi, I've read the discussion in the RFC and let me state that I'm not a lawyer either, but from GPLv2 and MIT I'd probably go for the latter if that works for you guys. My understanding is that GPLv2 would come with mode headaches regarding stating changes and including the original source etc etc which I too would hate if I were to make use of a project like that. Since most of the code is from Apple and the virtual camera addition has no serious IP that I'd want to protect, I'm fine with people using it however they want. WDYT?

**Comment by gxalpha** [comment]
I agree.

**Comment by signalwerk** [comment]
👌yes! MIT for the win!

**Comment by lvsti** [comment]
FYI https://github.com/lvsti/CoreMediaIO-DAL-Example/pull/13

**Pull request closed without merging**
